export const PRODUCTOS = 'PRODUCTOS';
export const PRODUCTOS_EXITO = 'PRODUCTOS_EXITO'; 
export const PRODUCTOS_FAIL = 'PRODUCTOS_FAIL'; 
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'; 
export const AGREGAR_PRODUCTO_FAIL = 'AGREGAR_PRODUCTO_FAIL'; 

export const LOGIN = 'LOGIN';
export const LOGIN_EXITO = 'LOGIN_EXITO'; 
export const LOGIN_FAIL = 'LOGIN_FAIL'; 

export const TIENDAS = 'TIENDAS';
export const TIENDAS_EXITO = 'TIENDAS_EXITO'; 
export const TIENDAS_FAIL = 'TIENDAS_FAIL'; 